backend/modules/diagnostician/controllers/InspectionController.php
<?php

namespace app\modules\diagnostician\controllers;

use Yii;

use common\models\Inspection;
use common\models\InspectionSearch;
use common\models\ComplaintsInspection;
use common\models\ResultInspection;
use common\models\HelthStatusInspection;
use common\models\FeedingStatusInspection;
use common\models\PeripheralLymphNodesStatusInspection;
use common\models\BodyMassIndexInspection;
use common\models\DysuriaInspection;
use common\models\SkinStatusInspection;
use common\models\EdemaInspection;
use common\models\ThyroidStatusInspection;
use common\models\MammaryGlandStatusInspection;
use common\models\OsteoarticularStatusInspection;
use common\models\StoolStatusInspection;
use common\models\TongueStatusInspection;
use common\models\GallbladderStatusInspection;
use common\models\KidneysStatusInspection;
use common\models\LiverStatusInspection;
use common\models\SpleenStatusInspection;
use common\models\StomachStatusInspection;
use common\models\Signature;



use common\models\GeneralInspection;
use common\models\NeurologicalInspection;
use common\models\LungsInspection;
use common\models\Patient;
use common\models\InspectionDocument;
use common\models\CardiovascularInspection;
use common\models\OtherInspection;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\Style\Font;
use PhpOffice\PhpWord\TemplateProcessor;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\Style\Alignment;
use Arslanim\TemplateMapper\DocumentMapper;

use app\modules\diagnostician\controllers\DefaultController;

/**
 * InspectionController implements the CRUD actions for Inspection model.
 */
class InspectionController extends DefaultController
{

    public $inspectionId;
    public $patientId;

    public $inspection;

    public function beforeAction($action) {

        $this->layout = 'main-inspection';

        /*$this->inspectionId = Yii::$app->getRequest()->getQueryParam('inspection_id');
        $this->patientId = Yii::$app->getRequest()->getQueryParam('patient_id');*/

        return parent::beforeAction($action);
    }

    public function actionPatient($patient_id) {
        $this->layout = 'main';

        $patient = $this->findPatient($patient_id);
        $searchModel = new InspectionSearch();
        $searchModel->patient_id = $patient_id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'patient' => $patient,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionIndex()
    {
        return $this->redirect(['/diagnostician']);
    }
    /**
     * Lists all Inspection models.
     * @return mixed
     */
    /*public function actionIndex($patient_id)
    {
        $this->layout = 'main';

        $patient = $this->findPatient($patient_id);
        $searchModel = new InspectionSearch();
        $searchModel->patient_id = $patient_id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'patient' => $patient,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }*/

    /**
     * Creates a new Inspection model.
     * If creation is successful, the browser will be redirected to the 'complaints' page.
     * @return mixed
     */
    public function actionCreate($patient_id)
    {
        $model = new Inspection();
        $patient = $this->findPatient($patient_id);
        $model->patient_id = $patient->id;
        if ($model->save()) {
            return $this->redirect(['complaints', 'inspection_id' => $model->id, 'patient_id' => $patient->id]);
        } else {
            Yii::$app->session->setFlash('error', 'Не удалось создать новый осмотр. Попробуйте еще раз или обратитесь к администратору.');
            return $this->redirect(['index', 'patient_id' => $patient->id]);
        }
    }

    public function actionComplaints($inspection_id, $patient_id) {

        $this->inspectionId = $inspection_id;
        $this->patientId = $patient_id;

        $inspection = $this->findModel($inspection_id, $patient_id);
        $model = $inspection->complaintsInspection;
        if ($model === null) {
            $model = new ComplaintsInspection();
            $model->inspection_id = $inspection_id;
            $model->patient_id = $patient_id;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Обновлено успешно');
            return $this->redirect(Yii::$app->request->referrer);
        } else {
            if ($model->hasErrors()) {
                Yii::$app->session->setFlash('error', $this->getModelErrorsToString($model->errors));
            }
            return $this->render('/complaints-inspection/_complaints_form', [
                'model' => $model,
            ]);    
        }
    }

    public function actionResultInspection($inspection_id, $patient_id) {

        $this->inspectionId = $inspection_id;
        $this->patientId = $patient_id;

        $inspection = $this->findModel($inspection_id, $patient_id);
        $model = $inspection->resultInspection;
        if ($model === null) {
            $model = new ResultInspection();
            $model->inspection_id = $inspection_id;
            $model->patient_id = $patient_id;
        } 

        $model->surveysIds = $model->getSurveyIds();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Обновлено успешно');
            return $this->redirect(Yii::$app->request->referrer);
        } else {
            if ($model->hasErrors()) {
                Yii::$app->session->setFlash('error', $this->getModelErrorsToString($model->errors));
            }
            return $this->render('/result-inspection/_result_inspection_form', [
                'model' => $model,
            ]);    
        }

    }

    public function actionHelthStatusInspection($inspection_id, $patient_id) {

        $this->inspectionId = $inspection_id;
        $this->patientId = $patient_id;

        $inspection = $this->findModel($inspection_id, $patient_id);
        $model = $inspection->helthStatusInspection;

        if ($model === null) {
            $model = new HelthStatusInspection();
            $model->inspection_id = $inspection_id;
            $model->patient_id = $patient_id;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Обновлено успешно');
            return $this->redirect(Yii::$app->request->referrer);
        } else {
            if ($model->hasErrors()) {
                Yii::$app->session->setFlash('error', $this->getModelErrorsToString($model->errors));
            }
            return $this->render('/helth-status-inspection/_helth_status_inspection_form', [
                'model' => $model,
            ]);    
        }

    }

    public function actionFeedingStatusInspection($inspection_id, $patient_id) {

        $this->inspectionId = $inspection_id;
        $this->patientId = $patient_id;

        $inspection = $this->findModel($inspection_id, $patient_id);
        $model = $inspection->feedingStatusInspection;

        if ($model === null) {
            $model = new FeedingStatusInspection();
            $model->inspection_id = $inspection_id;
            $model->patient_id = $patient_id;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Обновлено успешно');
            return $this->redirect(Yii::$app->request->referrer);
        } else {
            if ($model->hasErrors()) {
                Yii::$app->session->setFlash('error', $this->getModelErrorsToString($model->errors));
            }
            return $this->render('/feeding-status-inspection/_feeding_status_inspection_form', [
                'model' => $model,
            ]);    
        }

    }

    public function actionPeripheralLymphNodesStatusInspection($inspection_id, $patient_id) {

        $this->inspectionId = $inspection_id;
        $this->patientId = $patient_id;

        $inspection = $this->findModel($inspection_id, $patient_id);
        $model = $inspection->peripheralLymphNodesStatusInspection;

        if ($model === null) {
            $model = new PeripheralLymphNodesStatusInspection();
            $model->inspection_id = $inspection_id;
            $model->patient_id = $patient_id;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Обновлено успешно');
            return $this->redirect(Yii::$app->request->referrer);
        } else {
            if ($model->hasErrors()) {
                Yii::$app->session->setFlash('error', $this->getModelErrorsToString($model->errors));
            }
            return $this->render('/peripheral-lymph-nodes-status-inspection/_peripheral_lymph_nodes_status_inspection_form', [
                'model' => $model,
            ]);    
        }

    }

    public function actionBodyMassIndexInspection($inspection_id, $patient_id) {

        $this->inspectionId = $inspection_id;
        $this->patientId = $patient_id;

        $inspection = $this->findModel($inspection_id, $patient_id);
        $model = $inspection->bodyMassIndexInspection;

        if ($model === null) {
            $model = new BodyMassIndexInspection();
            $model->inspection_id = $inspection_id;
            $model->patient_id = $patient_id;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Обновлено успешно');

backend/modules/diagnostician/controllers/PatientController.php
<?php

namespace app\modules\diagnostician\controllers;

use Yii;
use common\models\Patient;
use common\models\PatientSearch;
use common\models\Contract;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\TemplateProcessor;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\Style\Alignment;
use Arslanim\TemplateMapper\DocumentMapper;
use app\modules\diagnostician\controllers\DefaultController;

/**
 * PatientController implements the CRUD actions for Patient model.
 */
class PatientController extends DefaultController
{
    /**
     * Lists all Patient models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PatientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Patient model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Patient model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Patient();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            
            return $this->redirect(['inspection/', 'patient_id' => $model->id]);
            //return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionCreateContract($patient_id) {
        $model = $this->findModel($patient_id);
        $contract = new Contract();
        $contract->patient_id = $patient_id;
        /*$maxContractNumber = Contract::find()
            ->select('contract_number')
            ->max('contract_number');
        if ($maxContractNumber) {
            $contract->contract_number = $maxContractNumber + 1;
        } else {
            $contract->contract_number = 1;
        }*/
        $contract->contract_date = date("Y-m-d");

        //if ($contract->save()) {

            //load template    
            $templateProcessor = new TemplateProcessor(Yii::getAlias('@uploads').'/patterns/contract.docx');

            $patientContractMapper = new DocumentMapper($templateProcessor, null, [
                ($model) ? ($model) : (new Patient),
                ($contract) ? ($contract) : (new Contract),
            ]);
            $patientContractMapper->mapObjects();

            $templateProcessor->saveAs(Yii::getAlias('@uploads').'/contracts/contract-' . $model->patient_name . '-' . $contract->contract_date . '.docx');

            $this->downloadContractFile(Yii::getAlias('@uploads').'/contracts/contract-' . $model->patient_name . '-' . $contract->contract_date . '.docx');

        //}
    }

    /**
     * Updates an existing Patient model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Patient model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Patient model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Patient the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Patient::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function downloadContractFile($filePath) {
        if (!empty($filePath)) {
            header("Content-type:application/doc");
            header('Content-Disposition: attachment; filename="'.basename($filePath).'"'); 
            header('Content-Length: ' . filesize($filePath));
            readfile($filePath);
            Yii::app()->end();
        }
    }
}

backend/modules/diagnostician/views/layouts/inspection.php
<?php

use kartik\sidenav\SideNav;
use common\widgets\Alert;
use yii\helpers\Html;
?>

<div class="row">
    <div class="col-md-3 inspection-list">
        
        <?php
            echo SideNav::widget([
                    'type' => SideNav::TYPE_DEFAULT,
                    'heading' => 'Карточка осмотра ' . Html::a('печать', ['print', 'inspection_id' => Yii::$app->controller->inspectionId, 'patient_id' => Yii::$app->controller->patientId], ['class' => 'btn btn-success btn-xs']),
                    'containerOptions' => [
                        'id' => 'inspection-sidenav',
                        //'class' => 'navbar-fixed-side navbar-fixed-side-left'
                    ],
                    'items' => [

                        [
                            'url' => ['inspection/complaints', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Жалобы и анамнез',
                        ],
                        [
                            'url' => [
                                'inspection/helth-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Общее состояние',
                        ],
                        [
                            'url' => [
                                'inspection/feeding-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Питание',
                        ],
                        [
                            'url' => [
                                'inspection/body-mass-index-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Индекс массы тела',
                        ],
                        [
                            'url' => [
                                'inspection/skin-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Кожные покровы',
                        ],
                        [
                            'url' => [
                                'inspection/edema-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Отёки',
                        ],
                        [
                            'url' => [
                                'inspection/peripheral-lymph-nodes-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Периферические лимфоузлы',
                        ],
                        [
                            'url' => [
                                'inspection/thyroid-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Щитовидная железа',
                        ],
                        [
                            'url' => [
                                'inspection/mammary-gland-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Молочные железы',
                        ],
                        [
                            'url' => [
                                'inspection/osteoarticular-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Костно-суставная система',
                        ],
                        [
                            'url' => [
                                'inspection/neurological-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Неврологический статус',
                        ],
                        [
                            'url' => [
                                'inspection/lungs-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Лёгкие',
                        ],
                        [
                            'url' => [
                                'inspection/cardiovascular-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Сердечно-сосудистая система',
                        ],
                        [
                            'url' => [
                                'inspection/tongue-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Язык',
                        ],
                        [
                            'url' => [
                                'inspection/stomach-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Живот',
                        ],
                        [
                            'url' => [
                                'inspection/liver-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Печень',
                        ],
                        [
                            'url' => [
                                'inspection/gallbladder-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Желчный пузырь',
                        ],
                        [
                            'url' => [
                                'inspection/spleen-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Селезёнка',
                        ],
                        [
                            'url' => [
                                'inspection/kidney-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Почки',
                        ],
                        [
                            'url' => [
                                'inspection/dysuria-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Дизурии',
                        ],
                        [
                            'url' => [
                                'inspection/stool-status-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Стул',
                        ],
                        [
                            'url' => [
                                'inspection/result-inspection', 
                                'inspection_id' => Yii::$app->controller->inspectionId,
                                'patient_id' => Yii::$app->controller->patientId
                            ],
                            'label' => 'Результаты осмотра',
                        ],
                        /*[
                            'url' => ['inspection/general-inspection', 'inspection_id' => Yii::$app->controller->inspectionId, 'patient_id' => Yii::$app->controller->patientId],
                            'label' => 'Основной осмотр',
                        ],
                        */
                    ],
                ]);
        ?>

    </div>
    <div class="col-md-9">
        <?= Alert::widget() ?>
        <?= $content ?>

    </div>
</div>

backend/modules/diagnostician/views/layouts/main-inspection.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AdminAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;
//use yii\widgets\Alert;


AdminAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body style="background-color: #EAEDEF">

<?php $this->beginBody() ?>

<div class="wrap">
    <?php
	
    NavBar::begin([
        'brandLabel' => 'Кабинет диагноста',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems[] = ['label' => 'Пациенты клиники', 'url' => ['patient/index']];
    $menuItems[] = ['label' => 'Рабочие кабинеты', 'url' => ['/site/login']];
	
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Вход', 'url' => ['/site/login']];
    } else {
        $menuItems[] = [
            'label' => 'Выход ( '.Yii::$app->user->identity->username.' )',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ];
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container full-width">
        <?php /*Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ])*/ ?>
        <?php //Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Система "Атлас-офис" <?= date('Y') ?></p>

        <p class="pull-right">
            <!--Разработано <a href="http://its-spc.ru">ИнтелТранс</a>-->
        </p>
    </div>
</footer>

<?php $this->endBody() ?>
<div id="backtop">&#9650;</div>
</body>
</html>
<?php $this->endPage() ?>

backend/modules/diagnostician/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AdminAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;
//use yii\widgets\Alert;


AdminAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>

<div class="wrap">
    <?php
	
    NavBar::begin([
        'brandLabel' => 'Кабинет диагноста',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems[] = ['label' => 'Пациенты клиники', 'url' => ['patient/index']];
    $menuItems[] = ['label' => 'Рабочие кабинеты', 'url' => ['/site/login']];
	
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Вход', 'url' => ['/site/login']];
    } else {
        $menuItems[] = [
            'label' => 'Выход ( '.Yii::$app->user->identity->username.' )',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ];
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Система "Атлас-офис" <?= date('Y') ?></p>

        <p class="pull-right">
            <!--Разработано <a href="http://its-spc.ru">ИнтелТранс</a>-->
        </p>
    </div>
</footer>

<?php $this->endBody() ?>
<div id="backtop">&#9650;</div>
</body>
</html>
<?php $this->endPage() ?>