backend/modules/administrator/controllers/PatientController.php
<?php

namespace app\modules\administrator\controllers;

use Yii;
use common\models\Patient;
use common\models\PatientSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PatientController implements the CRUD actions for Patient model.
 */
class PatientController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Patient models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PatientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Patient model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Patient model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Patient();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Patient model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Patient model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Patient model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Patient the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Patient::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/administrator/controllers/SurveyController.php
<?php

namespace app\modules\administrator\controllers;

use Yii;
use common\models\Survey;
use common\models\SurveySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

use app\modules\administrator\controllers\DefaultController;

/**
 * SurveyController implements the CRUD actions for Survey model.
 */
class SurveyController extends DefaultController
{
    /**
     * Lists all Survey models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SurveySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Survey model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Survey model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Survey();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Creates a new Survey model through modal form.
     * If creation is successful, the browser will be redirected to the 'index' page.
     * Else, if creation wasn't successfull -> if there was errors - set json heade response and return formated errors
     * Else this is first handling -> render form through ajax
     * @return mixed
     */
    public function actionCreateModal() {
        $model = new Survey();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Запись добавлена!');
            return $this->redirect(['index']);
        } else {
            if ($model->hasErrors()) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return $this->getModelErrorsToString($model->errors);
            } else {
                return $this->renderAjax('_modal_form', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Updates an existing Survey model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Survey model through modal form.
     * If update is successful, the browser will be redirected to the 'index' page.
     * Else, if creation wasn't successfull -> if there was errors - set json heade response and return formated errors
     * Else this is first handling -> render form through ajax
     * @param integer $id
     * @return mixed
     */
    public function actionUpdateModal($id) {
        $model = Survey::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            if ($model->hasErrors()) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return $this->getModelErrorsToString($model->errors);
            } else {
                return $this->renderAjax('_modal_form', [
                    'model' => $model,
                ]);                
            }
        }
    }

    /**
     * Deletes an existing Survey model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (!$this->findModel($id)->delete()) {
            Yii::$app->session->setFlash('warning', 'Невозможно удалить запись, т.к. она используется!');
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the Survey model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Survey the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Survey::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Parse model errors to string
     * @param integer $id
     * @return Survey model errors string
     */
    protected function getModelErrorsToString($errors) {
        $errorString = "";
        foreach ($errors as $error) {
            for ($i = 0, $maxi = count($error); $i < $maxi; $i++) {
                $errorString .= $error[$i]."\r\n";
            }
        }
        return $errorString;
    }
}

backend/modules/administrator/controllers/UserController.php
<?php

namespace app\modules\administrator\controllers;

use Yii;
use app\modules\administrator\models\User;
use app\modules\administrator\models\UserSearch;
use app\modules\administrator\models\AuthAssignment;
use common\models\Administrator;
//use common\models\User;


use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\modules\administrator\models\SignupForm;
use app\modules\administrator\controllers\DefaultController;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends DefaultController
{
	 /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


	public function actionProfile($id)
    {
        $model = $this->findModel($id);
		$profile = AuthAssignment::find()->where(['user_id'=>$id])->one();
			
		switch($profile->item_name){
			case 'administrator':
				$this->redirect(['administrator/view', 'id' => $id]);
				break;
		}
    }
	
    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
        	if ($model->resetPassword) {
        		$model->password = $model->resetPassword;
        	}
        	$model->save();
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
		$model=$this->findModel($id);
        if ($model->id==Yii::$app->user->identity->id) {
            Yii::$app->getSession()->setFlash('error', 'Невозможно удалить свой профайл');
        } else {
            $model->delete();
        }
	   return $this->redirect(['index']); 
    } 


    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
	public function actionSignup() {
        /*$model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Запись добавлена!');
            return $this->redirect(['index']);
        } else {
            return $this->render('signup', [
                'model' => $model,
            ]);
        }*/
		$model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
				$userRole = Yii::$app->authManager->getRole($model->role_name);
				Yii::$app->authManager->assign($userRole, $user->getId());

				switch($model->role_name){
					case 'administrator': {
                        //create default user profile
                        $profile = new Administrator();
                        $profile->user_id = $user->getId();
                        $profile->save();
                        $this->redirect(['administrator/update', 'id' => $profile->user_id]);
                    }break;
				}

				return;
			}	
        }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }
	
    protected function getAdministratorById($id) 
    {
        if (($model = Administrator::findOne($id)) !== null){
            return $model;
        }else{
        	throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
     

    protected function getEditorById($id) {
        if (($model = Editor::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function getAuthorById($id) 
    {
        if(($model = Author::findOne($id)) !== null) {
            return $model;
        }else{
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
		
}

backend/modules/administrator/views/layouts/inspection.php
<?php

use kartik\sidenav\SideNav;

?>

<div class="row">
    <div class="col-md-0">
        
        <?php
            /*echo SideNav::widget([
                    'type' => SideNav::TYPE_DEFAULT,
                    'heading' => 'Навигация по осмотрам',
                    'containerOptions' => [
                        'id' => 'inspection-sidenav',
                        //'class' => 'navbar-fixed-side navbar-fixed-side-left'
                    ],
                    'items' => [
                        [
                            'url' => '#patient-info',
                            'label' => 'Данные пациента',
                        ],
                        [
                            'url' => '#patient-complaints',
                            'label' => 'Жалобы пациента',
                        ],
                        [
                            'url' => '#patient-anamnesis',
                            'label' => 'Анамнез',
                        ],
                        [
                            'url' => '#inspection-results',
                            'label' => 'Результаты осмотра',
                        ],
                        [
                            'label' => 'Основной осмотр',
                        ],
                        [
                            'url' => '#neorological-status',
                            'label' => 'Неврологический статус',
                        ],
                    ],
                ]);*/
        ?>

    </div>
    <div class="col-md-12">
        
        <?= $content ?>

    </div>
</div>

backend/modules/administrator/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AdminAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use kartik\nav\NavX;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;
//use yii\widgets\Alert;


AdminAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>

<div class="wrap">
    <?php

        NavBar::begin([
            'brandLabel' => 'Кабинет администратора',
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-inverse navbar-fixed-top',
            ],
        ]);

            //$menuItems[] = ['label' => 'Пациенты клиники', 'url' => ['patient/index']];
            $menuItems[] = ['label' => 'Справочники', 'url' => ['index'],
                'items' => [
                    ['label' => 'Неврологический статус', 
                        'items' => [
                            ['label' => 'ПНП', 'url' => ['finger-nose-status/index']],
                            ['label' => 'Движения в конечностях', 'url' => ['extremities-movement-status/index']],
                            ['label' => 'Разница зрачков', 'url' => ['pupils-diff-status/index']],
                            ['label' => 'Реакция зрачков', 'url' => ['pupils-reaction-status/index']],
                        ]
                    ],
                    ['label' => 'Лёгкие', 
                        'items' => [
                            ['label' => 'Аускультативно', 'url' => ['lungs-auscultation-status/index']],
                            ['label' => 'Хрипы', 'url' => ['crepitation-status/index']],
                            ['label' => 'Перкуторно', 'url' => ['percussion-status/index']],
                            ['label' => 'Грудная клетка', 'url' => ['rib-cage-status/index']],
                            ['label' => 'Голосовое дрожание', 'url' => ['voice-trembling-status/index']],
                        ]
                    ],
                    ['label' => 'Сердечно-сосудистая система', 
                        'items' => [
                            ['label' => 'Сердце', 'url' => ['heart-status/index']],
                            ['label' => 'Тоны сердца', 'url' => ['heart-tones-status/index']],
                            ['label' => 'Акцент тонов сердца', 'url' => ['heart-tones-accent-status/index']],
                            ['label' => 'Шумы сердца', 'url' => ['heart-noises-status/index']],
                        ]
                    ],
                    ['label' => 'Общее состояние здоровья', 'url' => ['helth-status/index']],
                    ['label' => 'Периферические лимфоузлы', 'url' => ['peripheral-lymph-nodes-status/index']],
                    ['label' => 'Кожные покровы', 'url' => ['skin-status/index']],
                    ['label' => 'Щитовидная железа', 'url' => ['thyroid-status/index']],
                    ['label' => 'Молочные железы', 'url' => ['mammary-status/index']],
                    ['label' => 'Костно-суставная система', 'url' => ['osteoarticular-system-status/index']],
                    ['label' => 'Стул', 'url' => ['stool-status/index']],
                    ['label' => 'Почки', 'url' => ['kidneys-status/index']],
                    ['label' => 'Селезёнка', 'url' => ['spleen-status/index']],
                    ['label' => 'Печень', 'url' => ['liver-status/index']],
                    ['label' => 'Язык', 'url' => ['tongue-status/index']],
                    ['label' => 'Питание', 'url' => ['feeding-status/index']],
                    ['label' => 'Желчный пузырь', 'url' => ['gallbladder-status/index']],
                    ['label' => 'Живот', 'url' => ['stomach-status/index']],
                    ['label' => 'Обследования', 'url' => ['survey/index']],
                ]
            ];
            $menuItems[] = ['label' => 'Пользователи', 'url' => ['user/index']];
            $menuItems[] = ['label' => 'Рабочие кабинеты', 'url' => ['/site/login']];
            
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Вход', 'url' => ['/site/login']];
            } else {
                $menuItems[] = [
                    'label' => 'Выход ( '.Yii::$app->user->identity->username.' )',
                    'url' => ['/site/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
            }

            echo NavX::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
                'activateParents' => true,
                'encodeLabels' => false
            ]);

        NavBar::end();
    /*NavBar::begin([
        'brandLabel' => 'Кабинет администратора',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-default navbar-fixed-top',
        ],
    ]);
    $menuItems[] = ['label' => 'Пациенты клиники', 'url' => ['patient/index']];
    $menuItems[] = ['label' => 'Справочники', 'url' => ['index'],
        'items' => [
            ['label' => 'Общее состояние здоровья', 'url' => ['helth-status/index']],
            ['label' => 'Периферические лимфоузлы', 'url' => ['peripheral-lymph-nodes-status/index']],
            ['label' => 'Лёгочные хрипы', 'url' => ['crepitation-status/index']],
            ['label' => 'Движения в конечностях', 'url' => ['extremities-movement-status/index']],
            ['label' => 'Питание', 'url' => ['feeding-status/index']],
            ['label' => 'ПНП (пальценосовая проба)', 'url' => ['finger-nose-status/index']],
            ['label' => 'Желчный пузырь', 'url' => ['gallbladder-status/index']],
            ['label' => 'Шумы сердца', 'url' => ['heart-noises-status/index']],
            ['label' => 'Сердце', 'url' => ['heart-status/index']],
            ['label' => 'Акцент тонов сердца', 'url' => ['heart-tones-accent-status/index']],
            ['label' => 'Тоны сердца', 'url' => ['heart-tones-status/index']],
            ['label' => 'Голосовое дрожание', 'url' => ['voice-trembling-status/index']],
            ['label' => 'Язык', 'url' => ['tongue-status/index']],
            ['label' => 'Щитовидная железа', 'url' => ['thyroid-status/index']],
            ['label' => 'Стул', 'url' => ['stool-status/index']],
            ['label' => 'Живот', 'url' => ['stomach-status/index']],
            ['label' => 'Обследования', 'url' => ['survey/index']],
        ]
    ];
    $menuItems[] = ['label' => 'Пользователи', 'url' => ['user/index']];
    $menuItems[] = ['label' => 'Рабочие кабинеты', 'url' => ['/site/login']];
	
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Вход', 'url' => ['/site/login']];
    } else {
        $menuItems[] = [
            'label' => 'Выход ( '.Yii::$app->user->identity->username.' )',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ];
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();*/
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Система "Атлас-офис" <?= date('Y') ?></p>

        <p class="pull-right">
            <!--Разработано <a href="http://its-spc.ru">ИнтелТранс</a>-->
        </p>
    </div>
</footer>

<?php $this->endBody() ?>
<div id="backtop">&#9650;</div>
</body>
</html>
<?php $this->endPage() ?>